require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Rails:
  Enabled: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/Documentation:
  Enabled: false
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Metrics/LineLength:
  Max: 130
RSpec/FilePath:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/ContextWording:
 Prefixes:
   - when
   - with
   - without
   - if
   - and


ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false